package sql;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author EskandarAtrakchi
 */
public class CustomerFirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFirstFrame
     */
    public CustomerFirstFrame() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        UserFFIDF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UPassWordFFF = new javax.swing.JPasswordField();
        jLabel47 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log-in");

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/addemployee.png"))); // NOI18N
        jButton2.setText("Login");
        jButton2.setToolTipText("Make sure to write the right info to login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 440, 110, 40);

        UserFFIDF.setBackground(new java.awt.Color(204, 204, 204));
        UserFFIDF.setForeground(new java.awt.Color(0, 0, 0));
        UserFFIDF.setToolTipText("your data here.");
        UserFFIDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserFFIDFMouseClicked(evt);
            }
        });
        UserFFIDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFFIDFActionPerformed(evt);
            }
        });
        UserFFIDF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserFFIDFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserFFIDFKeyTyped(evt);
            }
        });
        jPanel1.add(UserFFIDF);
        UserFFIDF.setBounds(160, 302, 190, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter User-ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 300, 100, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        jButton4.setText("Register");
        jButton4.setToolTipText("Click me to register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(380, 440, 120, 39);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter PassWord");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 360, 120, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/logout.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.setToolTipText("Shut down ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 440, 100, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.setToolTipText("Clear the fields above ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 440, 110, 40);

        UPassWordFFF.setBackground(new java.awt.Color(204, 204, 204));
        UPassWordFFF.setForeground(new java.awt.Color(0, 0, 0));
        UPassWordFFF.setToolTipText("your data here.");
        UPassWordFFF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UPassWordFFFKeyPressed(evt);
            }
        });
        jPanel1.add(UPassWordFFF);
        UPassWordFFF.setBounds(160, 360, 190, 30);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel47.setToolTipText("Logo");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(670, 10, 70, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/test.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 760, 510);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        jMenu1.setText("Can't login?");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (CustomerFirstFrame.UserFFIDF.getText().isEmpty() == true || CustomerFirstFrame.UPassWordFFF.getText().isEmpty() == true) {

            JOptionPane.showMessageDialog(null, "Try to fill out all the fields please!");
        } else {

            SQL.loginVerificationforCustomer();
            this.setSize(0, 0);
            this.setLocation(10000, 10000);

        }

        /*
        String username = "admin";
        String password = "123";
        if(jTextField1.getText().matches(username) && jTextField2.getText().matches(password)) {
            
            System.out.println("Welcome, admin!");
            this.dispose();
            Customers.main(null);
            
        } else {
            System.out.println("Invalid username or password.");
        }
         */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserFFIDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFFIDFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UserFFIDFActionPerformed

    private void UserFFIDFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserFFIDFKeyPressed

        int lengthPIN = UserFFIDF.getText().length();

        if (lengthPIN == 4) {

            UserFFIDF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }

    }//GEN-LAST:event_UserFFIDFKeyPressed

    private void UserFFIDFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserFFIDFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            evt.consume();

        }

    }//GEN-LAST:event_UserFFIDFKeyTyped

    private void UserFFIDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFFIDFMouseClicked

        JOptionPane.showMessageDialog(null, "Digits only!");

    }//GEN-LAST:event_UserFFIDFMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        UserFFIDF.setText(null);
        UPassWordFFF.setText(null);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        this.dispose();
        RegisterationForm.main(null);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void UPassWordFFFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UPassWordFFFKeyPressed

        int lengthPIN = UPassWordFFF.getText().length();

        if (lengthPIN == 10) {

            UPassWordFFF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }

    }//GEN-LAST:event_UPassWordFFFKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        this.dispose();
        NewJFrame.main(null);

    }//GEN-LAST:event_jMenu1MouseClicked

    public void actionPerformed(ActionEvent e) {

        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPasswordField UPassWordFFF;
    public static javax.swing.JTextField UserFFIDF;
    public static javax.swing.JMenu date;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel47;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JMenu time;
    // End of variables declaration//GEN-END:variables
}
