package sql;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author EskandarAtrakchi
 */
public class Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    public Customers() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }

    public void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        UPasswordF = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        UViewBTNInM = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UAddressF = new javax.swing.JTextField();
        UIDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        UPhoneNoF = new javax.swing.JTextField();
        UERICodeF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UDOBLYear = new javax.swing.JTextField();
        UMonthDOBF = new javax.swing.JTextField();
        UDayDOBF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        YearEXPDate = new javax.swing.JTextField();
        MonthUserEXPDateF = new javax.swing.JTextField();
        DayEXPDateUserF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UCardNOF = new javax.swing.JTextField();
        UDOFL = new javax.swing.JLabel();
        UCardEXPDateL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UCCVBankCardF = new javax.swing.JTextField();
        UserNameF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        VSID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LiveViewCBTN1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        LightMode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer frame");

        jPanel6.setLayout(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/men.png"))); // NOI18N
        jPanel6.add(jLabel21);
        jLabel21.setBounds(120, 150, 500, 350);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/logout.png"))); // NOI18N
        jButton1.setText("Logout ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(600, 640, 110, 50);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel44.setToolTipText("Logo");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(650, 10, 70, 80);

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/2910857.jpg"))); // NOI18N
        jPanel6.add(jLabel24);
        jLabel24.setBounds(-10, 0, 740, 770);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("LOG-OUT", jPanel1);

        jPanel7.setLayout(null);

        UPasswordF.setBackground(new java.awt.Color(204, 204, 204));
        UPasswordF.setForeground(new java.awt.Color(0, 0, 0));
        UPasswordF.setToolTipText("your data here.");
        UPasswordF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UPasswordFKeyPressed(evt);
            }
        });
        jPanel7.add(UPasswordF);
        UPasswordF.setBounds(160, 100, 210, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Your password");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(70, 100, 105, 30);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton11.setText("Clear");
        jButton11.setToolTipText("Button action to clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);
        jButton11.setBounds(470, 580, 110, 40);

        UViewBTNInM.setBackground(new java.awt.Color(204, 204, 204));
        UViewBTNInM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UViewBTNInM.setForeground(new java.awt.Color(0, 0, 0));
        UViewBTNInM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        UViewBTNInM.setText("View");
        UViewBTNInM.setToolTipText("Button action to view");
        UViewBTNInM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UViewBTNInMActionPerformed(evt);
            }
        });
        jPanel7.add(UViewBTNInM);
        UViewBTNInM.setBounds(350, 580, 110, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Phone No.");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(90, 250, 96, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/update icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setToolTipText("Button action to update");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(590, 580, 120, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ERI-Code");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(430, 250, 51, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Your-address");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(400, 180, 92, 30);

        UAddressF.setBackground(new java.awt.Color(204, 204, 204));
        UAddressF.setForeground(new java.awt.Color(0, 0, 0));
        UAddressF.setToolTipText("your data here.");
        UAddressF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UAddressFKeyPressed(evt);
            }
        });
        jPanel7.add(UAddressF);
        UAddressF.setBounds(490, 180, 200, 30);

        UIDF.setEditable(false);
        UIDF.setBackground(new java.awt.Color(204, 204, 204));
        UIDF.setForeground(new java.awt.Color(0, 0, 0));
        UIDF.setText("CLICK ME TO VIEW YOOUR ID");
        UIDF.setToolTipText("Your ID is here and it is not edit-able");
        UIDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UIDFMouseClicked(evt);
            }
        });
        jPanel7.add(UIDF);
        UIDF.setBounds(490, 100, 200, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Your-ID");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(430, 100, 44, 30);

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("Show password");
        jToggleButton1.setToolTipText("BTN action to hide your password for security reasons");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton1);
        jToggleButton1.setBounds(10, 60, 116, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Password is hidden for security reasons");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(160, 60, 216, 30);

        UPhoneNoF.setBackground(new java.awt.Color(204, 204, 204));
        UPhoneNoF.setForeground(new java.awt.Color(0, 0, 0));
        UPhoneNoF.setToolTipText("your data here.");
        UPhoneNoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPhoneNoFActionPerformed(evt);
            }
        });
        UPhoneNoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UPhoneNoFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UPhoneNoFKeyTyped(evt);
            }
        });
        jPanel7.add(UPhoneNoF);
        UPhoneNoF.setBounds(160, 250, 210, 30);

        UERICodeF.setBackground(new java.awt.Color(204, 204, 204));
        UERICodeF.setForeground(new java.awt.Color(0, 0, 0));
        UERICodeF.setToolTipText("your data here.");
        UERICodeF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UERICodeFKeyPressed(evt);
            }
        });
        jPanel7.add(UERICodeF);
        UERICodeF.setBounds(490, 250, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Your-DOB");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(410, 370, 57, 30);

        UDOBLYear.setBackground(new java.awt.Color(204, 204, 204));
        UDOBLYear.setForeground(new java.awt.Color(0, 0, 0));
        UDOBLYear.setToolTipText("your data here.");
        UDOBLYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDOBLYearActionPerformed(evt);
            }
        });
        UDOBLYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UDOBLYearKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UDOBLYearKeyTyped(evt);
            }
        });
        jPanel7.add(UDOBLYear);
        UDOBLYear.setBounds(480, 370, 64, 30);

        UMonthDOBF.setBackground(new java.awt.Color(204, 204, 204));
        UMonthDOBF.setForeground(new java.awt.Color(0, 0, 0));
        UMonthDOBF.setToolTipText("your data here.");
        UMonthDOBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMonthDOBFActionPerformed(evt);
            }
        });
        UMonthDOBF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMonthDOBFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UMonthDOBFKeyTyped(evt);
            }
        });
        jPanel7.add(UMonthDOBF);
        UMonthDOBF.setBounds(550, 370, 64, 30);

        UDayDOBF.setBackground(new java.awt.Color(204, 204, 204));
        UDayDOBF.setForeground(new java.awt.Color(0, 0, 0));
        UDayDOBF.setToolTipText("your data here.");
        UDayDOBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDayDOBFActionPerformed(evt);
            }
        });
        UDayDOBF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UDayDOBFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UDayDOBFKeyTyped(evt);
            }
        });
        jPanel7.add(UDayDOBF);
        UDayDOBF.setBounds(620, 370, 64, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Card EXP Date");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(390, 520, 89, 30);

        YearEXPDate.setBackground(new java.awt.Color(204, 204, 204));
        YearEXPDate.setForeground(new java.awt.Color(0, 0, 0));
        YearEXPDate.setToolTipText("your data here.");
        YearEXPDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEXPDateActionPerformed(evt);
            }
        });
        YearEXPDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YearEXPDateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YearEXPDateKeyTyped(evt);
            }
        });
        jPanel7.add(YearEXPDate);
        YearEXPDate.setBounds(480, 520, 64, 30);

        MonthUserEXPDateF.setBackground(new java.awt.Color(204, 204, 204));
        MonthUserEXPDateF.setForeground(new java.awt.Color(0, 0, 0));
        MonthUserEXPDateF.setToolTipText("your data here.");
        MonthUserEXPDateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthUserEXPDateFActionPerformed(evt);
            }
        });
        MonthUserEXPDateF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MonthUserEXPDateFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MonthUserEXPDateFKeyTyped(evt);
            }
        });
        jPanel7.add(MonthUserEXPDateF);
        MonthUserEXPDateF.setBounds(550, 520, 64, 30);

        DayEXPDateUserF.setBackground(new java.awt.Color(204, 204, 204));
        DayEXPDateUserF.setForeground(new java.awt.Color(0, 0, 0));
        DayEXPDateUserF.setToolTipText("your data here.");
        DayEXPDateUserF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayEXPDateUserFActionPerformed(evt);
            }
        });
        DayEXPDateUserF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DayEXPDateUserFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DayEXPDateUserFKeyTyped(evt);
            }
        });
        jPanel7.add(DayEXPDateUserF);
        DayEXPDateUserF.setBounds(620, 520, 64, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Bank card No.");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(70, 440, 90, 30);

        UCardNOF.setBackground(new java.awt.Color(204, 204, 204));
        UCardNOF.setForeground(new java.awt.Color(0, 0, 0));
        UCardNOF.setToolTipText("your data here.");
        UCardNOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCardNOFActionPerformed(evt);
            }
        });
        UCardNOF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UCardNOFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UCardNOFKeyTyped(evt);
            }
        });
        jPanel7.add(UCardNOF);
        UCardNOF.setBounds(160, 440, 210, 30);

        UDOFL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UDOFL.setForeground(new java.awt.Color(153, 153, 153));
        UDOFL.setText("YYYY-MM-DD");
        UDOFL.setToolTipText("your data here.");
        jPanel7.add(UDOFL);
        UDOFL.setBounds(480, 340, 78, 30);

        UCardEXPDateL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UCardEXPDateL.setForeground(new java.awt.Color(153, 153, 153));
        UCardEXPDateL.setText("YYYY-MM-DD");
        UCardEXPDateL.setToolTipText("your data here.");
        jPanel7.add(UCardEXPDateL);
        UCardEXPDateL.setBounds(480, 490, 78, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Your name");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(90, 180, 72, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Bank card CCV No.");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(40, 520, 120, 30);

        UCCVBankCardF.setBackground(new java.awt.Color(204, 204, 204));
        UCCVBankCardF.setForeground(new java.awt.Color(0, 0, 0));
        UCCVBankCardF.setToolTipText("your data here.");
        UCCVBankCardF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCCVBankCardFActionPerformed(evt);
            }
        });
        UCCVBankCardF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UCCVBankCardFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UCCVBankCardFKeyTyped(evt);
            }
        });
        jPanel7.add(UCCVBankCardF);
        UCCVBankCardF.setBounds(160, 520, 210, 30);

        UserNameF.setBackground(new java.awt.Color(204, 204, 204));
        UserNameF.setForeground(new java.awt.Color(0, 0, 0));
        UserNameF.setToolTipText("your data here.");
        UserNameF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserNameFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserNameFKeyTyped(evt);
            }
        });
        jPanel7.add(UserNameF);
        UserNameF.setBounds(160, 180, 210, 30);

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/DOT.gif"))); // NOI18N
        jLabel16.setText("Attention: Numbers only!");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(20, 10, 180, 30);
        jLabel16.setVisible(false);

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton16.setText("Un-register me ");
        jButton16.setToolTipText("Button action to delete your data");
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton16);
        jButton16.setBounds(180, 580, 160, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/Payment.png"))); // NOI18N
        jButton3.setText("Add Card");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(25, 580, 140, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel45.setToolTipText("Logo");
        jPanel7.add(jLabel45);
        jLabel45.setBounds(650, 0, 70, 80);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/wallpaper.jpg"))); // NOI18N
        jPanel7.add(jLabel26);
        jLabel26.setBounds(0, 0, 730, 730);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("MANAGE", jPanel2);

        jPanel9.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/DOT.gif"))); // NOI18N
        jLabel11.setText("Digits only!");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(210, 40, 90, 30);
        jLabel11.setVisible(false);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/logout.png"))); // NOI18N
        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9);
        jButton9.setBounds(630, 280, 90, 40);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8);
        jButton8.setBounds(520, 280, 100, 40);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        jButton7.setText("Purchase");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);
        jButton7.setBounds(390, 280, 116, 39);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(0, 90, 730, 160);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/Search.png"))); // NOI18N
        jButton6.setText("Search-Vehicle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);
        jButton6.setBounds(210, 280, 170, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Vehicle-ID");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(20, 20, 59, 16);

        VSID.setBackground(new java.awt.Color(204, 204, 204));
        VSID.setForeground(new java.awt.Color(0, 0, 0));
        VSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VSIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VSIDKeyTyped(evt);
            }
        });
        jPanel9.add(VSID);
        VSID.setBounds(20, 40, 190, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/car-shipping-image-1166.jpg"))); // NOI18N
        jPanel9.add(jLabel17);
        jLabel17.setBounds(-10, 360, 750, 370);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel46.setToolTipText("Logo");
        jPanel9.add(jLabel46);
        jLabel46.setBounds(650, 0, 70, 80);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/blackBG.jpg"))); // NOI18N
        jPanel9.add(jLabel22);
        jLabel22.setBounds(0, 0, 740, 660);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("PURCHASE", jPanel5);

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Capacity", "Color", "Price", "Condition", "Size", "Model"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        LiveViewCBTN1.setBackground(new java.awt.Color(204, 204, 204));
        LiveViewCBTN1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LiveViewCBTN1.setForeground(new java.awt.Color(0, 0, 0));
        LiveViewCBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        LiveViewCBTN1.setText("Live-view");
        LiveViewCBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiveViewCBTN1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel47.setToolTipText("Logo");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("All the vehicles in the store will be displayed in here.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(LiveViewCBTN1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LiveViewCBTN1)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("VIEW", jPanel4);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        LightMode.setText("Light-mode");
        LightMode.setToolTipText("Clcik me to switch the mode");
        LightMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LightModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(LightMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "You have logged out successfully!");
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        SQL.update();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void UIDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UIDFMouseClicked

        Customers.UIDF.setText(CustomerFirstFrame.UserFFIDF.getText());

    }//GEN-LAST:event_UIDFMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        SQL.viewforCustomers();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        VSID.setText(null);
        jButton7.setEnabled(false);
        jTextArea3.setText(null);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextArea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea3MouseClicked

        jTextArea3.setEditable(false);

    }//GEN-LAST:event_jTextArea3MouseClicked

    private void UViewBTNInMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UViewBTNInMActionPerformed

        SQL.viewCustomerDetails();

    }//GEN-LAST:event_UViewBTNInMActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        SQL.ClearCustomerFields();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        SQL.ToggleBTNForPassWord();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        JOptionPane.showMessageDialog(null, "You have logged out successfully!");
        System.exit(0);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        jButton7.setEnabled(false);
        VSID.setEditable(false);
        CustomerPurchaseConfirmation.main(null);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void UDOBLYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UDOBLYearActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UDOBLYearActionPerformed

    private void UMonthDOBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMonthDOBFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UMonthDOBFActionPerformed

    private void UDayDOBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UDayDOBFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UDayDOBFActionPerformed

    private void YearEXPDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearEXPDateActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_YearEXPDateActionPerformed

    private void MonthUserEXPDateFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthUserEXPDateFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_MonthUserEXPDateFActionPerformed

    private void DayEXPDateUserFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayEXPDateUserFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_DayEXPDateUserFActionPerformed

    private void UDOBLYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UDOBLYearKeyPressed

        int lengthPIN = UDOBLYear.getText().length();

        if (lengthPIN == 4) {

            UDOBLYear.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_UDOBLYearKeyPressed

    private void UMonthDOBFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMonthDOBFKeyPressed

        int lengthPIN = UMonthDOBF.getText().length();

        if (lengthPIN == 2) {

            UMonthDOBF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }

    }//GEN-LAST:event_UMonthDOBFKeyPressed

    private void UDayDOBFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UDayDOBFKeyPressed

        int lengthPIN = UDayDOBF.getText().length();

        if (lengthPIN == 2) {

            UDayDOBF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }

    }//GEN-LAST:event_UDayDOBFKeyPressed

    private void YearEXPDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearEXPDateKeyPressed

        int lengthPIN = YearEXPDate.getText().length();

        if (lengthPIN == 4) {

            YearEXPDate.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }

    }//GEN-LAST:event_YearEXPDateKeyPressed

    private void MonthUserEXPDateFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonthUserEXPDateFKeyPressed

        int lengthPIN = MonthUserEXPDateF.getText().length();

        if (lengthPIN == 2) {

            MonthUserEXPDateF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }

    }//GEN-LAST:event_MonthUserEXPDateFKeyPressed

    private void DayEXPDateUserFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DayEXPDateUserFKeyPressed

        int lengthPIN = DayEXPDateUserF.getText().length();

        if (lengthPIN == 2) {

            DayEXPDateUserF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }

    }//GEN-LAST:event_DayEXPDateUserFKeyPressed

    private void UDOBLYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UDOBLYearKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UDOBLYearKeyTyped

    private void UMonthDOBFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMonthDOBFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UMonthDOBFKeyTyped

    private void UDayDOBFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UDayDOBFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UDayDOBFKeyTyped

    private void YearEXPDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearEXPDateKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_YearEXPDateKeyTyped

    private void MonthUserEXPDateFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonthUserEXPDateFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_MonthUserEXPDateFKeyTyped

    private void DayEXPDateUserFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DayEXPDateUserFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_DayEXPDateUserFKeyTyped

    private void VSIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VSIDKeyPressed

        int lengthPIN = VSID.getText().length();

        if (lengthPIN == 5) {

            VSID.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 5 digits");

        }

    }//GEN-LAST:event_VSIDKeyPressed

    private void VSIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VSIDKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel11.setVisible(true);
            evt.consume();

        } else {

            jLabel11.setVisible(false);

        }

    }//GEN-LAST:event_VSIDKeyTyped

    private void UPhoneNoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPhoneNoFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UPhoneNoFActionPerformed

    private void UPhoneNoFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UPhoneNoFKeyPressed

        int lengthPIN = UPhoneNoF.getText().length();

        if (lengthPIN == 10) {

            UPhoneNoF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }

    }//GEN-LAST:event_UPhoneNoFKeyPressed

    private void UPhoneNoFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UPhoneNoFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UPhoneNoFKeyTyped

    private void UPasswordFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UPasswordFKeyPressed

        int lengthPIN = UPasswordF.getText().length();

        if (lengthPIN == 14) {

            UPasswordF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 14 digits");

        }

    }//GEN-LAST:event_UPasswordFKeyPressed

    private void UAddressFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UAddressFKeyPressed

        int lengthPIN = UAddressF.getText().length();

        if (lengthPIN == 10) {

            UAddressF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }
    }//GEN-LAST:event_UAddressFKeyPressed

    private void UERICodeFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UERICodeFKeyPressed

        int lengthPIN = UERICodeF.getText().length();

        if (lengthPIN == 8) {

            UERICodeF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 8 Char");

        }
    }//GEN-LAST:event_UERICodeFKeyPressed

    private void UserNameFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameFKeyPressed

        int lengthPIN = UserNameF.getText().length();

        if (lengthPIN == 10) {

            UserNameF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 Char");

        }

    }//GEN-LAST:event_UserNameFKeyPressed

    private void UCCVBankCardFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UCCVBankCardFKeyPressed

        int lengthPIN = UCCVBankCardF.getText().length();

        if (lengthPIN == 3) {

            UCCVBankCardF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 3 digits");

        }

    }//GEN-LAST:event_UCCVBankCardFKeyPressed

    private void UCCVBankCardFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCCVBankCardFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UCCVBankCardFActionPerformed

    private void UCardNOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCardNOFActionPerformed

        JOptionPane.showMessageDialog(null, "Please, type numbers only!");

    }//GEN-LAST:event_UCardNOFActionPerformed

    private void UCardNOFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UCardNOFKeyPressed

        int lengthPIN = UCardNOF.getText().length();

        if (lengthPIN == 10) {

            UCardNOF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }

    }//GEN-LAST:event_UCardNOFKeyPressed

    private void UCCVBankCardFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UCCVBankCardFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UCCVBankCardFKeyTyped

    private void UCardNOFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UCardNOFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel16.setVisible(true);
            evt.consume();

        } else {

            jLabel16.setVisible(false);

        }

    }//GEN-LAST:event_UCardNOFKeyTyped

    private void UserNameFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameFKeyTyped

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {

            evt.consume();

        }

    }//GEN-LAST:event_UserNameFKeyTyped

    private boolean isLightMode = true;

    private void LightModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LightModeMouseClicked

        jLabel22.setVisible(!isLightMode);
        jLabel26.setVisible(!isLightMode);
        //jLabel23.setVisible(!isLightMode);

        //CustomerPurchaseConfirmation.jLabel11.setVisible(!isLightMode); 
        // note: will have to create an object to be able to toggle other labels in other frames 
        LightMode.setText(isLightMode ? "Dark-mode" : "Light-mode");
        isLightMode = !isLightMode;

    }//GEN-LAST:event_LightModeMouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        SQL.deleteUser();
        JOptionPane.showMessageDialog(null, "Attention, you have been out of the system.");
        System.exit(0);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void LiveViewCBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiveViewCBTN1ActionPerformed

        LiveViewCBTN1.setText("Refresh?");
        SQL.viewpanelVehicles();

    }//GEN-LAST:event_LiveViewCBTN1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        LiveViewCBTN1.setText("Live-view");
        SQL.cleartable();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        SQL.addCreditCard();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField DayEXPDateUserF;
    private javax.swing.JMenu LightMode;
    private javax.swing.JButton LiveViewCBTN1;
    public static javax.swing.JTextField MonthUserEXPDateF;
    public static javax.swing.JTextField UAddressF;
    public static javax.swing.JTextField UCCVBankCardF;
    public static javax.swing.JLabel UCardEXPDateL;
    public static javax.swing.JTextField UCardNOF;
    public static javax.swing.JTextField UDOBLYear;
    public static javax.swing.JLabel UDOFL;
    public static javax.swing.JTextField UDayDOBF;
    public static javax.swing.JTextField UERICodeF;
    public static javax.swing.JTextField UIDF;
    public static javax.swing.JTextField UMonthDOBF;
    public static javax.swing.JPasswordField UPasswordF;
    public static javax.swing.JTextField UPhoneNoF;
    public static javax.swing.JButton UViewBTNInM;
    public static javax.swing.JTextField UserNameF;
    public static javax.swing.JTextField VSID;
    public static javax.swing.JTextField YearEXPDate;
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextArea jTextArea3;
    public static javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenu time;
    // End of variables declaration//GEN-END:variables
}
