package sql;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author escan
 */
public class EmployeeFirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeFirstFrame
     */
    public EmployeeFirstFrame() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }

    public void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        EmployeeF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log-in");

        jPanel1.setLayout(null);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.setToolTipText("Action BTN to clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 100, 100, 40);

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setToolTipText("Action BTN to cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(140, 100, 102, 39);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/addemployee.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setToolTipText("Action BTN to login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 100, 110, 39);

        EmployeeF1.setBackground(new java.awt.Color(204, 204, 204));
        EmployeeF1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeF1.setForeground(new java.awt.Color(0, 0, 0));
        EmployeeF1.setToolTipText("your ID data here.");
        EmployeeF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeF1MouseClicked(evt);
            }
        });
        EmployeeF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeF1ActionPerformed(evt);
            }
        });
        EmployeeF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmployeeF1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmployeeF1KeyTyped(evt);
            }
        });
        jPanel1.add(EmployeeF1);
        EmployeeF1.setBounds(180, 40, 170, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee User-ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 50, 101, 16);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel47.setToolTipText("Logo");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(780, 10, 70, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/bk2.jpg"))); // NOI18N
        jLabel3.setText("Employees login");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 870, 530);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        jMenu1.setText("Can't login?");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (EmployeeF1.getText().isEmpty() == true) {

            JOptionPane.showMessageDialog(null, "Attention! field cannot be empty!");

        } else {

            this.dispose();
            SQL.loginVerificationforEmployees();

        }


        /*
        String username = "admin";
        String password = "123";
        if(jTextField1.getText().matches(username) && jTextField2.getText().matches(password)) {
            System.out.println("Welcome, admin!");
            this.dispose();
            Employees.main(null);
        } else {
            System.out.println("Invalid username or password.");
        }
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EmployeeF1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EmployeeF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmployeeF1KeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            evt.consume();

        }

    }//GEN-LAST:event_EmployeeF1KeyTyped

    private void EmployeeF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeF1ActionPerformed
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
    }//GEN-LAST:event_EmployeeF1ActionPerformed

    private void EmployeeF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmployeeF1KeyPressed

        int lengthPIN = EmployeeF1.getText().length();

        if (lengthPIN == 4) {

            EmployeeF1.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_EmployeeF1KeyPressed

    private void EmployeeF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeF1MouseClicked
        JOptionPane.showMessageDialog(null, "Digits only!");
    }//GEN-LAST:event_EmployeeF1MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        this.dispose();
        NewJFrame.main(null);

    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeFirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField EmployeeF1;
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu time;
    // End of variables declaration//GEN-END:variables
}
