/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author escan
 */
public class RegisterationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterationForm
     */
    public RegisterationForm() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }

    public void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EPassWordF = new javax.swing.JPasswordField();
        ECIDF = new javax.swing.JTextField();
        ECAddressF = new javax.swing.JTextField();
        ECPhoneNOF = new javax.swing.JTextField();
        ECERICodeF = new javax.swing.JTextField();
        ECYearDOB = new javax.swing.JTextField();
        ECMonthDOB = new javax.swing.JTextField();
        ECDayDOB = new javax.swing.JTextField();
        ECNameF = new javax.swing.JTextField();
        EXPYearECF = new javax.swing.JTextField();
        EXPMonthECF = new javax.swing.JTextField();
        EXPDayECF = new javax.swing.JTextField();
        ECCCVNOF = new javax.swing.JTextField();
        ECCardNOF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        EUDOBFORMATL = new javax.swing.JLabel();
        EUEXPFORMATL = new javax.swing.JLabel();
        ECVIDAWCF = new javax.swing.JTextField();
        ECVL = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        VLiveViewCBTN = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        LightMode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registeration frame ");

        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Customer password");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(60, 100, 120, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Customer-ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 100, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Customer address");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 170, 110, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ERI-Code");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(460, 240, 60, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Customer name");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(430, 170, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Customer-DOB");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(430, 350, 90, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Customer phone number ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 240, 150, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Customer CCV number");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 440, 140, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Card EXP date");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(440, 440, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Customer card number");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 350, 140, 30);

        EPassWordF.setBackground(new java.awt.Color(204, 204, 204));
        EPassWordF.setForeground(new java.awt.Color(0, 0, 0));
        EPassWordF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EPassWordFKeyPressed(evt);
            }
        });
        jPanel2.add(EPassWordF);
        EPassWordF.setBounds(180, 100, 200, 30);

        ECIDF.setBackground(new java.awt.Color(204, 204, 204));
        ECIDF.setForeground(new java.awt.Color(0, 0, 0));
        ECIDF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECIDFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECIDFKeyTyped(evt);
            }
        });
        jPanel2.add(ECIDF);
        ECIDF.setBounds(530, 100, 200, 30);

        ECAddressF.setBackground(new java.awt.Color(204, 204, 204));
        ECAddressF.setForeground(new java.awt.Color(0, 0, 0));
        ECAddressF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECAddressFKeyPressed(evt);
            }
        });
        jPanel2.add(ECAddressF);
        ECAddressF.setBounds(180, 170, 200, 30);

        ECPhoneNOF.setBackground(new java.awt.Color(204, 204, 204));
        ECPhoneNOF.setForeground(new java.awt.Color(0, 0, 0));
        ECPhoneNOF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECPhoneNOFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECPhoneNOFKeyTyped(evt);
            }
        });
        jPanel2.add(ECPhoneNOF);
        ECPhoneNOF.setBounds(180, 240, 200, 30);

        ECERICodeF.setBackground(new java.awt.Color(204, 204, 204));
        ECERICodeF.setForeground(new java.awt.Color(0, 0, 0));
        ECERICodeF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECERICodeFKeyPressed(evt);
            }
        });
        jPanel2.add(ECERICodeF);
        ECERICodeF.setBounds(530, 240, 200, 30);

        ECYearDOB.setBackground(new java.awt.Color(204, 204, 204));
        ECYearDOB.setForeground(new java.awt.Color(0, 0, 0));
        ECYearDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECYearDOBKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECYearDOBKeyTyped(evt);
            }
        });
        jPanel2.add(ECYearDOB);
        ECYearDOB.setBounds(530, 350, 64, 30);

        ECMonthDOB.setBackground(new java.awt.Color(204, 204, 204));
        ECMonthDOB.setForeground(new java.awt.Color(0, 0, 0));
        ECMonthDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECMonthDOBKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECMonthDOBKeyTyped(evt);
            }
        });
        jPanel2.add(ECMonthDOB);
        ECMonthDOB.setBounds(600, 350, 64, 30);

        ECDayDOB.setBackground(new java.awt.Color(204, 204, 204));
        ECDayDOB.setForeground(new java.awt.Color(0, 0, 0));
        ECDayDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECDayDOBKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECDayDOBKeyTyped(evt);
            }
        });
        jPanel2.add(ECDayDOB);
        ECDayDOB.setBounds(670, 350, 60, 30);

        ECNameF.setBackground(new java.awt.Color(204, 204, 204));
        ECNameF.setForeground(new java.awt.Color(0, 0, 0));
        ECNameF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECNameFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECNameFKeyTyped(evt);
            }
        });
        jPanel2.add(ECNameF);
        ECNameF.setBounds(530, 170, 200, 30);

        EXPYearECF.setBackground(new java.awt.Color(204, 204, 204));
        EXPYearECF.setForeground(new java.awt.Color(0, 0, 0));
        EXPYearECF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EXPYearECFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EXPYearECFKeyTyped(evt);
            }
        });
        jPanel2.add(EXPYearECF);
        EXPYearECF.setBounds(530, 440, 64, 30);

        EXPMonthECF.setBackground(new java.awt.Color(204, 204, 204));
        EXPMonthECF.setForeground(new java.awt.Color(0, 0, 0));
        EXPMonthECF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EXPMonthECFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EXPMonthECFKeyTyped(evt);
            }
        });
        jPanel2.add(EXPMonthECF);
        EXPMonthECF.setBounds(600, 440, 64, 30);

        EXPDayECF.setBackground(new java.awt.Color(204, 204, 204));
        EXPDayECF.setForeground(new java.awt.Color(0, 0, 0));
        EXPDayECF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EXPDayECFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EXPDayECFKeyTyped(evt);
            }
        });
        jPanel2.add(EXPDayECF);
        EXPDayECF.setBounds(670, 440, 60, 30);

        ECCCVNOF.setBackground(new java.awt.Color(204, 204, 204));
        ECCCVNOF.setForeground(new java.awt.Color(0, 0, 0));
        ECCCVNOF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECCCVNOFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECCCVNOFKeyTyped(evt);
            }
        });
        jPanel2.add(ECCCVNOF);
        ECCCVNOF.setBounds(180, 440, 210, 30);

        ECCardNOF.setBackground(new java.awt.Color(204, 204, 204));
        ECCardNOF.setForeground(new java.awt.Color(0, 0, 0));
        ECCardNOF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECCardNOFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECCardNOFKeyTyped(evt);
            }
        });
        jPanel2.add(ECCardNOF);
        ECCardNOF.setBounds(180, 350, 210, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/addemployee.png"))); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(580, 580, 120, 40);

        EUDOBFORMATL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EUDOBFORMATL.setForeground(new java.awt.Color(153, 153, 153));
        EUDOBFORMATL.setText("YYYY-MM-DD");
        jPanel2.add(EUDOBFORMATL);
        EUDOBFORMATL.setBounds(530, 410, 100, 30);

        EUEXPFORMATL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EUEXPFORMATL.setForeground(new java.awt.Color(153, 153, 153));
        EUEXPFORMATL.setText("YYYY-MM-DD");
        jPanel2.add(EUEXPFORMATL);
        EUEXPFORMATL.setBounds(530, 320, 90, 30);

        ECVIDAWCF.setBackground(new java.awt.Color(204, 204, 204));
        ECVIDAWCF.setForeground(new java.awt.Color(0, 0, 0));
        ECVIDAWCF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ECVIDAWCFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ECVIDAWCFKeyTyped(evt);
            }
        });
        jPanel2.add(ECVIDAWCF);
        ECVIDAWCF.setBounds(530, 510, 200, 30);

        ECVL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ECVL.setForeground(new java.awt.Color(153, 153, 153));
        ECVL.setText("Vehicle-ID associated with the customer");
        jPanel2.add(ECVL);
        ECVL.setBounds(290, 510, 240, 30);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 204));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/DOT.gif"))); // NOI18N
        jLabel36.setText("Numbers only!");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(300, 580, 120, 40);
        jLabel36.setVisible(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(445, 580, 120, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N
        jLabel48.setToolTipText("Logo");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(650, 0, 70, 80);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/wallpaper.jpg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(-10, 0, 760, 750);

        jTabbedPane1.addTab("MANAGE-CUSTOMERS", jPanel2);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/logo.gif"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Vehicle displayer");

        VLiveViewCBTN.setBackground(new java.awt.Color(204, 204, 204));
        VLiveViewCBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VLiveViewCBTN.setForeground(new java.awt.Color(0, 0, 0));
        VLiveViewCBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/folder.png"))); // NOI18N
        VLiveViewCBTN.setText("Live-view");
        VLiveViewCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLiveViewCBTNActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/erase-128.png"))); // NOI18N
        jButton13.setText("Clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/logout.png"))); // NOI18N
        jButton20.setText("Exit");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Capacity", "Color", "Price", "Condition", "Size", "Model"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton20)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(VLiveViewCBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VLiveViewCBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addComponent(jLabel47))
                .addContainerGap(616, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(143, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("VIEW-VEHICLES", jPanel4);

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        LightMode.setText("Light-mode");
        LightMode.setToolTipText("Clcik me to switch the mode");
        LightMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LightModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(LightMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EPassWordFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EPassWordFKeyPressed

        int lengthPIN = EPassWordF.getText().length();

        if (lengthPIN == 10) {

            EPassWordF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }
    }//GEN-LAST:event_EPassWordFKeyPressed

    private void ECIDFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECIDFKeyPressed

        int lengthPIN = ECIDF.getText().length();

        if (lengthPIN == 4) {

            ECIDF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_ECIDFKeyPressed

    private void ECIDFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECIDFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECIDFKeyTyped

    private void ECAddressFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECAddressFKeyPressed

        int lengthPIN = ECAddressF.getText().length();

        if (lengthPIN == 10) {

            ECAddressF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 char");

        }
    }//GEN-LAST:event_ECAddressFKeyPressed

    private void ECPhoneNOFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECPhoneNOFKeyPressed

        int lengthPIN = ECPhoneNOF.getText().length();

        if (lengthPIN == 10) {

            ECPhoneNOF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }
    }//GEN-LAST:event_ECPhoneNOFKeyPressed

    private void ECPhoneNOFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECPhoneNOFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECPhoneNOFKeyTyped

    private void ECERICodeFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECERICodeFKeyPressed

        int lengthPIN = ECERICodeF.getText().length();

        if (lengthPIN == 10) {

            ECERICodeF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 char");

        }
    }//GEN-LAST:event_ECERICodeFKeyPressed

    private void ECYearDOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECYearDOBKeyPressed

        int lengthPIN = ECYearDOB.getText().length();

        if (lengthPIN == 4) {

            ECYearDOB.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_ECYearDOBKeyPressed

    private void ECYearDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECYearDOBKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECYearDOBKeyTyped

    private void ECMonthDOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECMonthDOBKeyPressed

        int lengthPIN = ECMonthDOB.getText().length();

        if (lengthPIN == 2) {

            ECMonthDOB.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }
    }//GEN-LAST:event_ECMonthDOBKeyPressed

    private void ECMonthDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECMonthDOBKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECMonthDOBKeyTyped

    private void ECDayDOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECDayDOBKeyPressed

        int lengthPIN = ECDayDOB.getText().length();

        if (lengthPIN == 2) {

            ECDayDOB.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }
    }//GEN-LAST:event_ECDayDOBKeyPressed

    private void ECDayDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECDayDOBKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECDayDOBKeyTyped

    private void ECNameFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECNameFKeyPressed

        int lengthPIN = ECNameF.getText().length();

        if (lengthPIN == 10) {

            ECNameF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 char");

        }
    }//GEN-LAST:event_ECNameFKeyPressed

    private void ECNameFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECNameFKeyTyped

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {

            evt.consume();

        }
    }//GEN-LAST:event_ECNameFKeyTyped

    private void EXPYearECFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPYearECFKeyPressed

        int lengthPIN = EXPYearECF.getText().length();

        if (lengthPIN == 4) {

            EXPYearECF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_EXPYearECFKeyPressed

    private void EXPYearECFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPYearECFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_EXPYearECFKeyTyped

    private void EXPMonthECFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPMonthECFKeyPressed

        int lengthPIN = EXPMonthECF.getText().length();

        if (lengthPIN == 2) {

            EXPMonthECF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }
    }//GEN-LAST:event_EXPMonthECFKeyPressed

    private void EXPMonthECFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPMonthECFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_EXPMonthECFKeyTyped

    private void EXPDayECFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPDayECFKeyPressed

        int lengthPIN = EXPDayECF.getText().length();

        if (lengthPIN == 2) {

            EXPDayECF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 2 digits");

        }
    }//GEN-LAST:event_EXPDayECFKeyPressed

    private void EXPDayECFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPDayECFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_EXPDayECFKeyTyped

    private void ECCCVNOFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECCCVNOFKeyPressed

        int lengthPIN = ECCCVNOF.getText().length();

        if (lengthPIN == 3) {

            ECCCVNOF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 3 digits");

        }
    }//GEN-LAST:event_ECCCVNOFKeyPressed

    private void ECCCVNOFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECCCVNOFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECCCVNOFKeyTyped

    private void ECCardNOFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECCardNOFKeyPressed

        int lengthPIN = ECCardNOF.getText().length();

        if (lengthPIN == 10) {

            ECCardNOF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 10 digits");

        }
    }//GEN-LAST:event_ECCardNOFKeyPressed

    private void ECCardNOFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECCardNOFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECCardNOFKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        SQL.addUnregisterationFormUser();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ECVIDAWCFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECVIDAWCFKeyPressed

        int lengthPIN = ECVIDAWCF.getText().length();

        if (lengthPIN == 4) {

            ECVIDAWCF.setText("");

            JOptionPane.showMessageDialog(null, "You cannot enter more than 4 digits");

        }
    }//GEN-LAST:event_ECVIDAWCFKeyPressed

    private void ECVIDAWCFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ECVIDAWCFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {

            jLabel36.setVisible(true);
            evt.consume();

        } else {

            jLabel36.setVisible(false);

        }
    }//GEN-LAST:event_ECVIDAWCFKeyTyped

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        SQL.cleartableForUnregistered();
        VLiveViewCBTN.setText("Live-view");

    }//GEN-LAST:event_jButton13ActionPerformed

    private void VLiveViewCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLiveViewCBTNActionPerformed

        RegisterationForm.VLiveViewCBTN.setText("Refresh?");
        SQL.viewpanelVehiclesForUnregistered();

    }//GEN-LAST:event_VLiveViewCBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        CustomerFirstFrame.main(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    Boolean isLightMode = false;

    private void LightModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LightModeMouseClicked

        jLabel16.setVisible(!isLightMode);
        jLabel16.setVisible(!isLightMode);
        //jLabel23.setVisible(!isLightMode);

        //CustomerPurchaseConfirmation.jLabel11.setVisible(!isLightMode);
        // note: will have to create an object to be able to toggle other labels in other frames
        LightMode.setText(isLightMode ? "Dark-mode" : "Light-mode");
        isLightMode = !isLightMode;

    }//GEN-LAST:event_LightModeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JTextField ECAddressF;
    protected static javax.swing.JTextField ECCCVNOF;
    protected static javax.swing.JTextField ECCardNOF;
    public static javax.swing.JTextField ECDayDOB;
    protected static javax.swing.JTextField ECERICodeF;
    protected static javax.swing.JTextField ECIDF;
    public static javax.swing.JTextField ECMonthDOB;
    protected static javax.swing.JTextField ECNameF;
    protected static javax.swing.JTextField ECPhoneNOF;
    protected static javax.swing.JTextField ECVIDAWCF;
    public static javax.swing.JLabel ECVL;
    public static javax.swing.JTextField ECYearDOB;
    public static javax.swing.JPasswordField EPassWordF;
    protected static javax.swing.JLabel EUDOBFORMATL;
    protected static javax.swing.JLabel EUEXPFORMATL;
    protected static javax.swing.JTextField EXPDayECF;
    protected static javax.swing.JTextField EXPMonthECF;
    protected static javax.swing.JTextField EXPYearECF;
    private javax.swing.JMenu LightMode;
    public static javax.swing.JButton VLiveViewCBTN;
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    protected static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    protected static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JMenu time;
    // End of variables declaration//GEN-END:variables
}
